### ISSUE TITLE
libusb_init fails

### ISSUE THREAD

**Issue by entrity** [Gritzman/libusb#3]
I see your instructions in the README:
1. you need to open device by UsbManager
2. open by libusb
3. close by libusb
4. close by UsbManager

The substeps for step number 2 are, as I understand them:
1. libusb_init
2. libusb_open_device_with_vid_pid

...but I encounter a problem when attempting to open the device with libusb: `libusb_init` returns `-99`.  I suppose that this is because my app lacks permissions to access `/dev/bus/usb`, but is there anything I can do about that?

**Comment by CAMOBAP** [comment]
@entrity on which version of Android OS you are testing?

**Comment by entrity** [comment]
@CAMOBAP795 : 6.0.1

**Comment by QiangliangHuang** [comment]
'setenforce 0'  in adb shell

**Comment by entrity** [comment]
Thanks. I've moved and left the project with others.
